config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#index'
  
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  validates :name, :cost, :country_origin, :presence => true

  scope :three_recent_products, -> { order(created_at: :desc).limit(3)}
  scope :usa_products, -> { where(country_origin: "United States of America")}

  scope :most_reviews, -> {(
    select("products.id, products.name, products.cost, products.country_origin, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
    )}
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product

  validates :author, :content_body, :rating, :presence => true
  validates_format_of :rating, :with => /[1-5]/, :on => :create, :message => 'must be a number between 1 and 5'
  validates_length_of :rating, :maximum => 1
  validates :content_body, length: { minimum: 50, maximum: 250 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @three_recent_products = Product.three_recent_products
    @usa_products = Product.usa_products
    @most_reviews = Product.most_reviews
    render :index
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added"
      redirect_to products_path
    else
      flash[:alert]= "Product was not created successfully"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated"
      redirect_to products_path
    else
      flash[:alert]= "Product was not updated successfully"
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product successfully deleted"
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :cost, :country_origin)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice]= "Review successfully added"
      redirect_to product_path(@review.product)
    else
      flash[:alert]= "Review was not successfully added"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice]= "Review successfully updated"
      redirect_to product_path(@review.product)
    else
      flash[:alert]= "Review was not successfully updated"
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice]= "Review successfully deleted"
    redirect_to product_path(@review.product)
  end

  private
    def review_params
      params.require(:review).permit(:author, :content_body, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= flash[:alert] %>
      <%= flash[:notice] %>
      <div class="bg-image">
        <div class="bg-opacity">
          <h1 class="centered">World Foods</h1>
        </div>
      </div>
      <br>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_errors.html.erb
<% if @product.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/products/_form.html.erb
<%= render "errors" %>

<%= form_for @product do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :cost %>
    <%= f.text_field :cost, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :country_origin %>
    <%= f.text_field :country_origin, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<% content_for(:title, "Edit Product | World's Foods") %>

<h1>Edit Product</h1>
<%= render "form" %>
<hr>

<p><%= link_to "Return to product", product_path %></p>

app/views/products/index.html.erb
<% content_for(:title, "Home | World Foods") %>

<div>
  <p>
    At World's Foods, we carefully evaluate each and every product we sell. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  </p>
  <p>
    We feature foods that are free of artificial preservatives, colors, flavors, sweeteners, and hydrogenated fats. We are passionate about great tasting food and the pleasure of sharing it with others. Ut enim ad minim veniam, quis nostrud exercitation. We are committed to foods that are wholesome and safe to eat.
  </p>
</div>
<hr>

<div class="row">
  <div class="col-sm-6">
    <div class="#">
      <h5>Most Reviewed Product</h5>
      <% if @most_reviews.any? %>
        <% @most_reviews.each do |product| %>
            <p><%= link_to product.name, product_path(product) %></p>
            <p>Cost: $<%= product.cost %> | Origin: <%= product.country_origin %></p>
        <% end %>
      <% else %>
        <p>There are no reviews at this point.</p>
      <% end %>
    </div>
    <br>
    <div>
      <h5>Recent Products</h5>
      <% if @three_recent_products.any? %>
        <% @three_recent_products.each do |product| %>
            <p><%= link_to product.name, product_path(product) %> </p>
        <% end %>
      <% else %>
        <p>There are no recent products.</p>
      <% end %>
    </div>
  </div>
  <div class="col-sm-6">
    <div>
      <h5>USA Products</h5>
      <% if @usa_products.any? %>
        <% @usa_products.each do |product| %>
            <p><%= link_to product.name, product_path(product) %></p>
        <% end %>
      <% else %>
        <p>There are no current products from the USA.</p>
      <% end %>
    </div>
  </div>
</div>
<hr>

<h3 class="centered">All Products</h3>
<h3 class="centered"><button class="btn btn-default"><%= link_to "Add Product", new_product_path %></button></h3>
  <% @products.each do |product| %>
    <p><%= link_to product.name, product_path(product) %></p>
  <% end %>

app/views/products/new.html.erb
<% content_for(:title, "Add Product | World's Foods") %>

<h1>Add Product</h1>

<%= render "form" %>
<hr>

<p><%= link_to "Return to products", products_path %></p>

app/views/products/show.html.erb
<% content_for(:title, "Product | World's Foods") %>

<div>
  <h1><%= @product.name %></h1>
  <p>Cost: <%= @product.cost %></p>
  <p>Origin: <%= @product.country_origin %></p>

  <button class="btn btn-default">
    <%= link_to "Edit", edit_product_path(@product) %>
  </button>
  <button class="btn btn-default">
    <%= link_to "Delete", product_path(@product), :data => {:confirm => "Please confirm deletion", :method => "delete"} %>
  </button>
</div>
<hr>

<div>
  <h3>Reviews <button class="btn btn-default"><%= link_to "Add Review", new_product_review_path(@product) %></button></h3>

  <%  if @product.reviews.any? %>
    <% @product.reviews.each do |review| %>
      <p>
        <div class="content_body">
          <%= review.content_body %>
          <div>
            <b>Author:</b> <%= review.author %> &nbsp | &nbsp <b>Rating:</b> <%= review.rating %>
          </div>
        </div>
        <div>
          <button class="btn btn-default">
            <%= link_to "edit", edit_product_review_path(@product, review) %>
          </button>
          <button class="btn btn-default">
            <%= link_to "delete", product_review_path(@product, review),
                                  :data => {:confirm => "Please confirm deletion",
                                                 :method => "delete"} %>
         </button>
       </div>
     </p>
     <br>
    <% end %>
  <% else %>
    <p>There are no reviews.</p>
  <% end %>
</div>
<hr>

<p><%= link_to "Return to homepage", products_path %></p>

app/views/reviews/_errors.html.erb
<% if @review.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @review.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/reviews/_form.html.erb
<%= render "errors" %>

<%= form_for [@product, @review] do |f| %>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content_body %>
    <%= f.text_field :content_body, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :rating %>
    <%= f.text_field :rating, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<% content_for(:title, "Edit Review | World's Foods") %>

<h1>Edit Review</h1>

<%= render "form" %>
<hr>

<p><%= link_to "Return to product page", product_path(@product) %></p>

app/views/reviews/new.html.erb
<% content_for(:title, "Add Review | World's Foods") %>

<h1>Add Review for "<%= @product.name %>"</h1>

<%= render 'form' %>
<hr>

<p><%= link_to "Return to product page", product_path(@product) %></p>